### DISCUSSION TITLE
Please make sure you have Wireguard installed on the host!!!

### DISCUSSION THREAD

**Discussion by alienfrenZyNo1** [bubuntux/nordlynx#118] [Show and tell]
I've been trying every solution under the sun in these discussions for the past 2 days. I finally seen someone talk about Wireguard and how it should be installed on the host. I did see Wireguard mentioned on the README. But holy shit, please make that MUST BE INSTALLED ON HOST bigger and in red and flashing or something!

https://www.wireguard.com/install/
For ubuntu the command is below:
`sudo apt install wireguard`

Remember, Wireguard has to be installed on the host (The OS of the vps or whatever that is holding all your containers). 

My docker-compose.yml that is working! The health check passes! So before you go and start adding all the extra env variables like I did, **MAKE SURE THAT WIREGUARD IS INSTALLED ON THE HOST!!!!**

```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    networks:
      - nordlynx_net
    cap_add:
      - NET_ADMIN #required
    ports:
      - 127.0.0.1:8081:8081
    environment:              
      - PRIVATE_KEY=[whateveryourprivatekeyis] #required
    healthcheck:
          test: ["CMD-SHELL", "curl https://api.nordvpn.com/vpn/check/full | grep '\"status\":\"Protected\"' && exit 0 || exit 1"]
    restart: unless-stopped 
networks:
  nordlynx_net:
    driver: bridge
    name: nordlynx_net
```

Hopefully I save someone a day or two!
