### DISCUSSION TITLE
Private Key using bubuntux/nordvpn:get_private_key

### DISCUSSION THREAD

**Discussion by PhamineXL** [bubuntux/nordlynx#130] [Q&A]
I'm running this Docker in Portainer.
What am I missing to get this to work?

```
version: "3"
services:
  vpn_key:
    image: bubuntux/nordvpn:get_private_key
    container_name: nordvpn_key
    cap_add:
      - NET_ADMIN    
      - NET_RAW
    environment:             
      - USER=user
      - PASS=pass
      - TOKEN=token
```

```
Waiting for daemon to start up...

  
Welcome to NordVPN! You can now connect to VPN by using 'nordvpn connect'.

  
Technology is already set to 'NORDLYNX'.

  
Connecting to United States #8641 (us8641.nordvpn.com)


  


Whoops! Connection failed. Please try again. If the problem persists, contact our customer support.
############################################################
Device "nordlynx" does not exist.
IP: 
Unable to access interface: No such device
Private Key: 
＼(＾O＾)／
############################################################

```
