### DISCUSSION TITLE
Torrent Downloading Fails - Trackers Unreachable

### DISCUSSION THREAD

**Discussion by davidnpayne** [bubuntux/nordlynx#133] [Q&A]
I'm having issues with my VPN container. NZBGet works fine but no torrent downloader works for me, I setup Firefox to test it too and the VPN container works for everything else but Torrents. I've tried Deluge, Transmission and qBittorrent. I'm focusing on qBittorrent right now. qBittorrent checks the torrent, but at the poin of downloading it downloads a few b/s or kb/s and then stalls and errors stating that all trackers are unreachable. I'm using extensions which all work fine for me, even in my other containers, there is no issue with the extensions. It's just downloading torrents. I've tried multiple servers and I have tried on my windows PC with qBittorrent going through the same VPN to the same server (which works fine). Any help would be appreciated.

```
---
version: "3.8"

########################### NETWORKS
 
networks:
  default:
    driver: bridge

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228
 
# Common environment values
x-environment: &default-tz-puid-pgid
     TZ: $TZ
     PUID: $PUID
     PGID: $PGID
 
# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  security_opt:
    - no-new-privileges:true
  restart: always
 
# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  network_mode: service:vpn
  depends_on:
      - vpn   
 
########################### SERVICES
services:  
# NORDVPN 
  vpn:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    container_name: vpn
    image: ghcr.io/bubuntux/nordlynx:latest
    cap_add:
      - NET_ADMIN               
      - NET_RAW 
      - SYS_MODULE              
    environment:
      - PRIVATE_KEY=$KEY
      - NET_LOCAL=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.5.0.2/32,172.17.0.0/16,172.23.0.0/16,192.168.68.0/16
      - ALLOWED_IPS=0.0.0.0/0,128.0.0.0/2
      - QUERY=filters\[country_id\]=104 #Ireland
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - PERSISTENT_KEEP_ALIVE=25
    ports:   
      - 8080:8080
      - 6881:6881 # Qbittorrent  
      - 6881:6881/udp # Qbittorrent  
      - 34400:34400 # XTEVE  
      - 6789:6789 # NZBGet  
      - 8081:8081 # Qbittorrent     
      - 9091:9091 # Transmission
      - 9091:9091/udp # Transmission      
      - 51414:51413 # Transmision
      - 51414:51413/udp # Transmision    
      - 3008:3000 # Firefox     
      - 3009:3001 # Firefox      
    volumes:
      - /lib/modules:/lib/modules:ro 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only

# NGINX
  web:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    container_name: web
    image: nginx

# qBittorrent - Torrent Downloader     
  qbittorrent:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8081
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $DOCKERDIR/qbittorrent:/config:rw
      - $DATADIR/media:/media:rw

# NZBGET - Usenet downloader  
  nzbget:
   <<: *common-keys-apps # See EXTENSION FIELDS at the top 
   image: linuxserver/nzbget
   container_name: nzbget
   volumes:
     - $DOCKERDIR/nzbget:/config
     - $DATADIR/media:/media
     - $DATADIR/media/downloads:/downloads
   environment:
     <<: *default-tz-puid-pgid
        
# Firefox   
  firefox:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: ghcr.io/linuxserver/firefox:latest
    container_name: firefox
    shm_size: "1gb"    
    volumes:
      - $DOCKERDIR/firefox:/config # config files 
    environment:
      <<: *default-tz-puid-pgid
```
