### DISCUSSION TITLE
can acces qbittorrent via localhost, but not IP

### DISCUSSION THREAD

**Discussion by uglyfish333** [bubuntux/nordlynx#141] [General]
Does anyone have an idea how I can fix this? I can access my qbittorent gui by going to 127.0.0.1:8089 or localhost:8089 on the machine the containers are running on, but trying to enter the local IP of the machine (e.g. 192.168.0.200) yields nothing. I know the IP is correct as it's reserved in my router and works just fine for SSH purposes. 

Here's what my docker compose file looks like:

 
    
```
version: "3.5"
services:
  nordvpn:
    container_name: NordLynx
    image: ghcr.io/bubuntux/nordlynx
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN #required
    ports:
      - "8089:8089" # QbitTorrent
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recommended if using ipv4 only
    environment:
      - PRIVATE_KEY=[42069]
      - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
      - NET_LOCAL=192.168.1.0/24
      - QUERY=filters\[country_id\]=153 # 153 is Netherlands based on country_id in https://api.nordvpn.com/v1/servers/recommendations
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: "service:nordvpn"
    container_name: QbitTorrent-Nord
    depends_on:
      - nordvpn
    environment:
      - WEBUI_PORT=8089
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    volumes:
      - /home/blah/qbit-nord/config:/config
      - /home/blah/downloads/torrents:/downloads
    restart: unless-stopped
```
