### DISCUSSION TITLE
Unable to pass traffic to WAN

### DISCUSSION THREAD

**Discussion by deserr** [bubuntux/nordlynx#150] [Q&A]
Noob here...

Can anyone take a look at this compose and identify why I have no traffic to WAN?

```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    hostname: nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN               # Required
      #- SYS_MODULE              # Maybe
    environment:
      - PRIVATE_KEY=xxxxxx
      - QUERY=filters\[country_id\]=140 #Mexico
      #- QUERY=filters\[country_id\]=14 #Austria
      - NET_LOCAL=192.168.1.0/24  # So it can be accessed within the local network
      - Allowed_IPS=0.0.0.0/1, 128.0.0.0/1
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')" 
    ports:
      - 8088:8088
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
      #- net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbit
    network_mode: service:nordlynx
    environment:
      - WEBUI_PORT=8088
      - PUID=1026
      - PGID=101
    volumes:
      - /volume2/docker/qbit/config:/config
      - /volume2/docker/qbit/downloads:/downloads
    depends_on:
      - nordlynx
    restart: unless-stopped
```

Nordlynx log shows the 'iptables' error.  Could this be the culprit?  Not sure how to correct. 

```
[2023-10-09T23:25:59+00:00] Connecting...
| [#]
| [#] ip link add wg0 type wireguard
| [#] wg setconf wg0 /dev/fd/63
| [#] ip -4 address add 10.5.0.2/32 dev wg0
| [#] ip link set mtu 1420 up dev wg0
| [#] resolvconf -a wg0 -m 0 -x
| [#] wg set wg0 fwmark 51820
| [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
| [#] ip -4 rule add not fwmark 51820 table 51820
| [#] ip -4 rule add table main suppress_prefixlength 0
| [#] iptables-restore -n
| iptables-restore v1.8.8 (legacy): iptables-restore: unable to initialize table 'raw'
|
| Error occurred at line: 1
| Try `iptables-restore -h' or 'iptables-restore --help' for more information.
| [#] resolvconf -d wg0 -f
| [#] ip -4 rule delete table 51820
| [#] ip -4 rule delete table main suppress_prefixlength 0
| [#] ip link delete dev wg0
| [2023-10-09T23:26:00+00:00] Connected! \(ᵔᵕᵔ)/
```
Here is my attempt to access WAN...

```
docker exec nordlynx  curl -sS --verbose google.com
*   Trying 142.250.72.46:80...
*   Trying [2607:f8b0:400f:804::200e]:80...
* Immediate connect fail for 2607:f8b0:400f:804::200e: Address not available
```

Routing table is clearly jacked...
```
root@DiskStation:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 ovs_eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 ovs_eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker-593838dc
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 ovs_eth0
```

I've read through the discussions here, but I'm coming up empty.  Thoughts?

Thanks folks!
