### DISCUSSION TITLE
Doesn't work if nordvpn client also running on host

### DISCUSSION THREAD

**Discussion by gauravojha** [bubuntux/nordlynx#173] [Q&A]
Does someone know why the following scenario doesn't work?

So I have a linux host with nordvpn cli running. It is connected to nordvpn servers. Now I bring up a container for nordlynx, and connected it to Netherlands. My docker container of nordlynx has no outside connectivity for some reason :confused: 

As soon as I turn off my host system's VPN, the connectivity starts to flow through. Is this something which is not supported? I have tried this using the nordvpn image as well, and that also doesn't work.

However, if I use this image, then it works - https://github.com/DyonR/docker-qbittorrentvpn.

This is the docker compose for this
```
---
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=<correct key>
      - QUERY=filters\[country_id\]=153
    devices:
      - /dev/net/tun
```
Quite interesting to see this.. I can ping, but I cannot reach? Would love to learn how this networking works
![image](https://github.com/user-attachments/assets/a4a60058-0ce6-4f5c-b612-00a85cef8f42)
