### DISCUSSION TITLE
Working proxy setup to remotely access a dependent container's WebUI?

### DISCUSSION THREAD

**Discussion by Legomaniac** [bubuntux/nordlynx#175] [General]
I have this nordlynx container setup and working with my deluge container to route it's traffic via NordVPN, yet allow the Deluge WebUI and server API to be accessible within my local network. Here is the relevant snippet of my docker compose file:
```
    nordlynx:
        image: ghcr.io/bubuntux/nordlynx
        hostname: nordlynx
        container_name: nordlynx
        ports:
            - 8112:8112
            - 58846:58846
        cap_add:
            - NET_ADMIN                             # required
            - SYS_MODULE                            # maybe
        environment:
            - PRIVATE_KEY=[[ redacted ]]                # required
            - QUERY=filters\[country_id\]=208&filters\[servers_groups\]\[identifier\]=legacy_p2p
            - NET_LOCAL=192.168.1.0/24
            - TZ=America/New_York
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1   # maybe
            - net.ipv4.conf.all.rp_filter=2        # maybe; set reverse path filter to loose mode
            - net.ipv6.conf.all.disable_ipv6=1     # disable ipv6; recommended if using ipv4 only
        restart: always
    deluge:
        image: lscr.io/linuxserver/deluge:latest
        network_mode: service:nordlynx
        container_name: deluge
        environment:
          - PUID=1001
          - PGID=1001
          - UMASK=022
          - TZ=Etc/UTC
          - DELUGE_LOGLEVEL=error #optional
        volumes:
          - /home/deluge/config:/config
          - /home/deluge/incoming:/downloads
        depends_on:
          - nordlynx
        restart: always
```

I can access the Deluge WebUI (port 8112) and server API (port 58846, for use with the Trireme Android app) from my local network just fine, the NET_LOCAL variable works as I would expect.

However, I have a DNS entry that is dynamically updated by a DDNS client that points to my home's IP address. I would like to be able to access the Deluge WebUI and API without updating the NET_LOCAL variable from every possible IP address I may want to access from (this sounds really tedious). 

For now I have just added the CIDR ranges for Verizon Wireless to my NET_LOCAL (`NET_LOCAL=192.168.1.0/24,174.192.0.0/10,75.192.0.0/10,75.96.0.0/11`). This works fine if I'm on my phone's 5G connection, but if I'm on somebody else's WiFi, I'll need to update the NET_LOCAL variable before I can use the Android app to interact with the Deluge server.

I have seen mention of setting up a proxy to forward traffic to get this to work. @Gunther-Shulz made a post here: https://github.com/bubuntux/nordlynx/discussions/105#discussioncomment-4301073 

> You need to add a forwarding proxy that is not in the same network namespace as the VPN to your docker-compose file and you set it to forward to the app that runs in the VPN namespace.

However, I have struggled to do this successfully. 
I have tried using the traefik example from here: https://github.com/bubuntux/nordvpn to no avail.

I'm hoping someone has gotten this working or can point me in the right direction to someone that has. Thanks!
