### DISCUSSION TITLE
Unable to access qbittorrent webui

### DISCUSSION THREAD

**Discussion by PedroLiu1999** [bubuntux/nordlynx#185] [Q&A]
I am trying to set up nordlynx with qbittorrent, and have followed the instruction to set NET_LOCAL and ALLOWED_IP.
My server is running on IP: 10.0.0.10, and the the log Nordlynx is connected.
But I can't access qbittorrent webui on 10.0.0.10:8282
Can someone help me with this please?
Blowe is the docker compse:

```
version:'3'

services:
    nordlynx:
        image: ghcr.io/bubuntux/nordlynx
        hostname: nordlynx
        container_name: nordlynx
        ports:
            - "8282:8080"
        cap_add:
            - NET_ADMIN
        environment:
            - PRIVATE_KEY=
            - QUERY=filters\[servers_groups\]\[identifier\]=legacy_p2p
            - NET_LOCAL=10.0.0.0/24
            - ALLOWED_IPS=0.0.0.0/0
            - TZ=Europe/London
			
    qbittorrent:
        hostname: qbittorrent
        image: hotio/qbittorrent:release-5.0.1
        depends_on:
        	- nordlynx
        network_mode: service:nordlynx
        restart: unless-stopped
	environment:
          - PGID=1000
          - PUID=1000
          - TZ=Europe/London
          - UMASK=002
        volumes:
          - /mnt/myDrive_sda1/DATA/AppData/qbittorrent/config:/config
          - /mnt/myDrive_sda1/DATA/Downloads/downloads
          - /mnt/myDrive_sda1/DATA/Media/media 
```
          
 Here are the log from the docker container:
 
 ```
nordlynx       | [migrations] started
nordlynx       | [migrations] no migrations found
nordlynx       | [2025-01-06T23:57:16+00:00] Firewall is up, everything has to go through the vpn
nordlynx       | usermod: no changes
nordlynx       | ───────────────────────────────────────
nordlynx       |   _____ __ __ _____ _____ _____ _____ 
nordlynx       |  |     |  |  |   __|_   _|     |     |
nordlynx       |  |   --|  |  |__   | | | |  |  | | | |
nordlynx       |  |_____|_____|_____| |_| |_____|_|_|_|
nordlynx       |        _____ __ __ _ __    ____  
nordlynx       |       | __  |  |  | |  |  |    \ 
nordlynx       |       | __ -|  |  | |  |__|  |  |
nordlynx       |       |_____|_____|_|_____|____/ 
nordlynx       | 
nordlynx       |   Based on images from linuxserver.io
nordlynx       | ───────────────────────────────────────
nordlynx       | 
nordlynx       | To support the app dev(s) visit:
nordlynx       | Bubuntux: https://github.com/sponsors/bubuntux
nordlynx       | WireGuard: https://www.wireguard.com/donations/
nordlynx       | To support LSIO projects visit:
nordlynx       | https://www.linuxserver.io/donate/
nordlynx       | 
nordlynx       | ───────────────────────────────────────
nordlynx       | GID/UID
nordlynx       | ───────────────────────────────────────
nordlynx       | 
nordlynx       | User UID:    911
nordlynx       | User GID:    911
nordlynx       | ───────────────────────────────────────
nordlynx       | [2025-01-06T23:57:16+00:00] Enabling connection to eth0 172.17.0.8/16
nordlynx       | [2025-01-06T23:57:16+00:00] Enabling connection to secure interfaces
nordlynx       | [2025-01-06T23:57:16+00:00] No interface network6 detected
nordlynx       | [2025-01-06T23:57:16+00:00] Enabling connection to network 10.0.0.0/24
nordlynx       | [custom-init] No custom files found, skipping...
nordlynx       | [ls.io-init] done.
nordlynx       | [2025-01-06T23:57:16+00:00] Finding the best server...
nordlynx       | [2025-01-06T23:57:17+00:00] Server: {...}
nordlynx       | [2025-01-06T23:57:17+00:00] Connecting...
nordlynx       | [#] 
nordlynx       | [#] ip link add wg0 type wireguard
nordlynx       | [#] wg setconf wg0 /dev/fd/63
nordlynx       | [#] ip -4 address add 10.5.0.2/32 dev wg0
nordlynx       | [#] ip link set mtu 1420 up dev wg0
nordlynx       | [#] resolvconf -a wg0 -m 0 -x
nordlynx       | [#] wg set wg0 fwmark 51820
nordlynx       | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
nordlynx       | [#] ip -4 rule add not fwmark 51820 table 51820
nordlynx       | [#] ip -4 rule add table main suppress_prefixlength 0
nordlynx       | [#] iptables-restore -n
nordlynx       | [#] 
nordlynx       | [2025-01-06T23:57:17+00:00] Connected! \(ᵔᵕᵔ)/
```
