### DISCUSSION TITLE
Accessing proxied container from internet

### DISCUSSION THREAD

**Discussion by nunsie** [bubuntux/nordlynx#61] [Q&A] [answered]
Hi,

My setup has an image that exposes port 3000, I've managed to get it behind the vpn and confirm its working correctly by curling the endpoint via localhost:3000.

I would now like to make this available over the internet, i've confirmed no fw rules are blocking port 3000 being access from the internet, and a server running on another container on port 4000 is accessible on my public IP but i just can't get access to my image behind the vpn.

compose:
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=[] #required

    ports:
      - 3000:3000 #web
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  web:
    image: some/image
    container_name: web
    network_mode: service:vpn
    restart: unless-stopped
    depends_on:
      - vpn
```
