### DISCUSSION TITLE
Nordlynx container as proxy to local browser

### DISCUSSION THREAD

**Discussion by cotangente** [bubuntux/nordlynx#64] [Q&A] [answered]
Hello,

I've been trying with no success to use a Nordlynx container as a proxy vpn for a specific profile in my local browser (firefox).

When I launch the container it says that connects ok to nordvpn:

`[2022-04-13T02:35:07+00:00] Connected! \(ᵔᵕᵔ)/`

but when I try to navigate from browser, container rejects connection.

I tried with this port config:

```
ports:
  - xxxx:51820
```
 
which port should I expose? maybe I'm missing something in sysctls?

This is my full docker-compose:

```
nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PRIVATE_KEY=xxxxxxxxxx
      - NET_LOCAL=192.168.10.0/24
      - QUERY=filters\[country_id\]=202
    ports:
      - 9191:51820
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: always
```

**Comment by yash-fn** [comment, marked as answer]
```yaml
version: '3'

services:

  nordvpn:
    image: bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY={PrivateKey} #required
      - QUERY=filters\[country_id\]=202
    restart: unless-stopped

  forwardproxy:
    image: soulteary/docker-nginx-forward-proxy
    depends_on:
      - nordvpn
    network_mode: 'service:nordvpn'
    restart: unless-stopped

networks:
  default:
```
Your Forward proxy will operate on container's port 80
