### DISCUSSION TITLE
NordLynx on QNAP

### DISCUSSION THREAD

**Discussion by rb-rookie** [bubuntux/nordlynx#84] [Show and tell]
As shown in https://github.com/bubuntux/nordlynx/discussions/41, you can get NordLynx Running on QNAP with the following

```
version: '3.3'
services:
    nordvpn:  
        container_name: NordLynx
        image: ghcr.io/bubuntux/nordlynx
        security_opt:
            - no-new-privileges:true
        cap_add:
            - NET_ADMIN #required
        ports:
            - '8222:9091'       # Transmision
            - '51413:51413'     # Transmision
            - '51413:51413/udp' # Transmision
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1  # Recommended if using ipv4 only
        environment:
            - PRIVATE_KEY=[REDACTED] #required
            - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
            - NET_LOCAL=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
            - QUERY=filters\[country_id\]=227 # 227 is UK based on country_id in https://api.nordvpn.com/v1/servers/recommendations
            - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
            - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"     
    transmission:
        image: ghcr.io/linuxserver/transmission
        network_mode: 'service:nordvpn'
        container_name: Transmission
        depends_on:
            - nordvpn
        environment:
            - PUID=1000
            - PGID=0
            - TZ=Europe/London
        volumes:
            - '/transmission/config:/config'
            - '/config/Downloads:/downloads'
            - '/transmission/watch:/watch'
        restart: unless-stopped
```
