### DISCUSSION TITLE
Leaks somewhere ?

### DISCUSSION THREAD

**Discussion by R-Nabil** [bubuntux/nordlynx#90] [Q&A]
Hi,

I have an auto-restart script that restarts my docker compose stacks on a regular basis.
Right around this time, I start to see my firewall dropping unallowed traffic that seems to be coming from the docker stack.
Could you help me figure out how ?

Here's the docker compose :

```
version: "2.1"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=<WG-PRIVATE-KEY>
      - ALLOWED_IPS=0.0.0.0/0 
      - NET_LOCAL= w.x.y.z/32
      - DNS=8.8.8.8
      - RECONNECT=21600                 
      - QUERY=filters\[country_id\]=97&filters\[servers_groups\]\[identifier\]=legacy_p2p
      - PERSISTENT_KEEP_ALIVE=25
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - <Port_1>:<Port_1>
      - <Port_2>:<Port_2>
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl https://api.nordvpn.com/vpn/check/full | grep '\"status\":\"Protected\"' && exit 0 || exit 1"]

  service1:
    image: service1
    container_name: service1
    network_mode: service:vpn
    environment:
      {....}
    volumes:
      {....}
    restart: always
    depends_on:
      - vpn
```
