### ISSUE TITLE
DNS leak when nordlynx is disconnected

### ISSUE THREAD

**Issue by krbrs** [bubuntux/nordlynx#101]
### **Describe the bug**
DNS is leaking when the container starts, can't say if it's the same when the connection drops
Same behavior as mentioned in https://github.com/bubuntux/nordvpn/issues/361
docker-compose was put together from different suggestions on the Wiki

### **Steps to reproduce**
- Start container from docker compose
- See DNS logs and find URLs from Containers called which are behind the nordlynx container until the connection is established

### **To Reproduce using docker-compose**
docker-compose.yml:
```
version: "3"
services:
  nordvpn:
    container_name: nordvpn
    image: ghcr.io/bubuntux/nordlynx:latest
    pull_policy: always
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      - QUERY=$QUERY
      - NET_LOCAL=$NET_LOCAL
      - ALLOWED_IPS=$ALLOWED_IPS
      - TZ=$TZ
      - PRIVATE_KEY=$PK
#     - DNS=$DNS # commented out as default has changed back to Nord servers
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
    ports:
      - **ports you need forwarded for behind containers**
```

I don't think the variables are important for troubleshooting, just set whichever fits your setup

### **Expected behavior**
No DNS leak at all even if nordvpn connection is down.
