### ISSUE TITLE
Super Slow Speed?

### ISSUE THREAD

**Issue by PJGitHub9** [bubuntux/nordlynx#111]
### **Describe the bug**
Using nordlynx and qbittorrent in wsl docker desktop... Speeds are crawling when i try to download a linux distro. My download speeds are 500mbps and the max download speeds im reaching are ~2MB/s.

### **To Reproduce using docker CLI**
running the YML file below. I had to add the nginx to the container because qbit wouldn't work without it for some reason. 

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
##VPN And Torrent
version: "3"
services:

  nordlynx:
    image: ghcr.io/bubuntux/nordlynx:latest
    container_name: nordlynx
    cap_add:
      - NET_ADMIN
    environment:
      - PRIVATE_KEY=privatekey
      - ALLOWED_IPS=0.0.0.0/1
      - NET_LOCAL=192.168.1.0/24
      - TZ= AMERICA/Toronto
      - DNS=103.86.96.100,103.86.99.100      
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6881:6881/udp
      - 6881:6881
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.rp_filter=2
    restart: unless-stopped
    
  web:
    image: nginx
    network_mode: "service:nordlynx"
    restart: unless-stopped
    
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    environment:
      - TZ= AMERICA/Toronto
      - PUID=1000
      - GUID=1000
      - Umask=022
    volumes:
      - /volume1/docker/qbit:/config
      - /mnt/d:/downloads
    restart: unless-stopped    
    network_mode: "service:nordlynx"
    depends_on:
      - nordlynx

    
# The torrent service would be available at http://localhost:8080/ 
# or anywhere inside of the local network http://192.168.1.xxx:8080
```

### **Expected behavior**
Reaching faster speeds

### **Logs**
```
nordlynx              | [2022-11-21T20:49:54+00:00] Connecting...
nordlynx              | [#]
nordlynx              | [#] ip link add wg0 type wireguard
nordlynx              | [#] wg setconf wg0 /dev/fd/63
nordlynx              | [#] ip -4 address add 10.5.0.2/32 dev wg0
nordlynx              | [#] ip link set mtu 1420 up dev wg0
nordlynx              | [#] resolvconf -a wg0 -m 0 -x
nordlynx              | [#] ip -4 route add 0.0.0.0/1 dev wg0
nordlynx              | [#]
nordlynx              | [2022-11-21T20:49:54+00:00] Connected! \(ᵔᵕᵔ)/
```

### **Additional context**
Ubuntu 22.04 (WSL), windows 11 22H2, docker desktop for windows
