### ISSUE TITLE
IP Adress is not shared to another container

### ISSUE THREAD

**Issue by DieSchoeneWolke** [bubuntux/nordlynx#115]
### **Describe the bug**
IP Adress is not shared to another container

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - ${CONNECT}
      - TECHNOLOGY=NordLynx
      - ${NETWORK}
      - PRIVATE_KEY=*censored*
    ports:
      - ${PORT1}:${PORT1}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    network_mode: ${NET}
      
  joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: ${RESTART}
    volumes:
      - ${VOLUME_PATH}/Joal/:/data/
    ports:
      - ${PORT2}:${PORT2}
    command: ["--joal-conf=/data", "--spring.main.web-environment=false", "--server.port=${PORT2}", "--joal.ui.path.prefix=", "--joal.ui.secret-token="]
    network_mode: ${NET}
```

### **Logs**
```
[2023-01-19T11:35:54+00:00] Connecting...
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#] 
[2023-01-19T11:35:54+00:00] Connected! \(ᵔᵕᵔ)/

```

### **Additional context**

The NordVPN Port is designated to 51820 in the .env file

nordvpn container
![image](https://user-images.githubusercontent.com/117728997/213435811-e3f486b0-8d3b-4f70-b203-d5ac89c4facd.png)

joal container
![image](https://user-images.githubusercontent.com/117728997/213433082-fcfbaa40-4358-4cd2-9f5c-eb8b089b0981.png)
