### ISSUE TITLE
Need to add public IPs to NET_LOCAL for it to work?

### ISSUE THREAD

**Issue by NoLooseEnds** [bubuntux/nordlynx#13]
### **Describe the bug**
This is my setup.
I have a "vpn-client" container, and I use `network_mode: "container:vpn-client"` to route the traffick of other containers. 
This worked perfectly with the nordvpn container.

I switched over to nordlynx, and this does not work properly. 

I've been trying to debug this now, and it looks like `NET_LOCAL` is not working properly?

If I want to use a custom DNS, i.e `1.1.1.1`, I have to add `1.1.1.0/24` to the `NET_LOCAL`. That makes it possible for all containers to resolve a hostname, but I can still not access the resolved IP (unless that is also added to `NET_LOCAL`).

This is the starting point:
```
version: '3.7'

services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordlynx
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - traefikproxy
      - vpn_internal
    environment:
      TZ: '${TZ}'
      PRIVATE_KEY: '${NORDPK}'     
```

I'll try to show a simple example: 

```
services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordlynx
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - traefikproxy
      - vpn_internal
    environment:
      TZ: '${TZ}'
      PRIVATE_KEY: '${NORDPK}' 

 # docker exec -ti vpn-client ping vg.no
^C%
```

```
services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordlynx
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - traefikproxy
      - vpn_internal
    environment:
      TZ: '${TZ}'
      PRIVATE_KEY: '${NORDPK}' 
      DNS: 1.1.1.1

 # docker exec -ti vpn-client ping vg.no
^C%
```

Does not work "out of the box" or with a set DNS.

If I add: `DNS: 1.1.1.1` _and_ `NET_LOCAL: 1.1.1.0/24` allowing the DNS IP-range. It works.
```
services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordlynx
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - traefikproxy
      - vpn_internal
    environment:
      TZ: '${TZ}'
      PRIVATE_KEY: '${NORDPK}' 
      DNS: 1.1.1.1
      NET_LOCAL: 1.1.1.0/24

# docker exec -ti vpn-client ping vg.no

PING vg.no (195.88.55.16): 56 data bytes
64 bytes from 195.88.55.16: icmp_seq=0 ttl=247 time=13.837 ms
64 bytes from 195.88.55.16: icmp_seq=1 ttl=247 time=11.964 ms
64 bytes from 195.88.55.16: icmp_seq=2 ttl=247 time=12.397 ms
64 bytes from 195.88.55.16: icmp_seq=3 ttl=247 time=11.672 ms
^C
--- vg.no ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 11.672/12.468/13.837/0.832 ms
```

I have also tried to load a page from a webserver, and that also works – but only if I've added the IP-range of the webserver in `NET_LOCAL`.

Not sure why it does not work, but something is off. 

Any help is appreciated!

EDIT: And it seems like that is revealing my local ISP ip-adress, ie. bypassing the VPN.
