### ISSUE TITLE
`ALLOW_LIST` does not work

### ISSUE THREAD

**Issue by schklom** [bubuntux/nordlynx#136]
### **Describe the bug**
I use the environment variable `ALLOW_LIST: icanhazip.com`. icanhazip.com displays the incoming IP.
When executing in the container `curl icanhazip.com`, I expect to see the server's IP, but it shows the VPN's IP instead.

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```yaml
version: '3'
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: vpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      PRIVATE_KEY: XXXXX
      PUBLIC_KEY: XXXXX
      END_POINT: XXXXX:51820
      ADDRESS: XXXXX
      DNS: 9.9.9.9
      ALLOW_LIST: "icanhazip.com"
      TZ: ${TZ}
```

### **Expected behavior**
My server's IP shows, not the VPN's IP.

### **Logs**
```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
[2023-06-10T23:02:28+00:00] Firewall is up, everything has to go through the vpn
Bubuntux: https://github.com/sponsors/bubuntux
WireGuard: https://www.wireguard.com/donations/
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

[2023-06-11T01:02:28+02:00] Enabling connection to eth1 192.168.58.2/24
[2023-06-11T01:02:29+02:00] Enabling connection to eth2 192.168.97.2/24
[2023-06-11T01:02:29+02:00] Enabling connection to eth0 192.168.113.2/24
[2023-06-11T01:02:29+02:00] Enabling connection to secure interfaces
[2023-06-11T01:02:29+02:00] No interface network6 detected
[2023-06-11T01:02:29+02:00] Enabling connection to host icanhazip.com
[custom-init] No custom files found, skipping...
[ls.io-init] done.
[2023-06-11T01:02:29+02:00] Connecting...
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.2.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#] 
[2023-06-11T01:02:29+02:00] Connected! \(ᵔᵕᵔ)/
```

### **Additional context**
Distribution used, versions, architecture and any other context about the problem here.

Debian GNU/Linux 11 (bullseye) runs on a arm64v8 Raspberry Pi 4
