### ISSUE TITLE
Access Jdownloader by nordlynx KO

### ISSUE THREAD

**Issue by titou4307** [bubuntux/nordlynx#140]
Hello

My container is marked Unhealthy and it impossible to access to internet by this container....

Here my config : 

```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN #required
      - NET_RAW # à confirmer
      - SYS_MODULE
    environment:
      - PRIVATE_KEY=fffffffffffffffffffffffffffffffffffffffffffffffffffffff=  #required
      - NET_LOCAL=192.168.1.0/24
      - TZ=Europe/France      
    ports:
      - 3129:3129 # jdownloader MyJdownloader
      - 5800:5800 # jdownloader web interface
      - 5801:5801 # à confirmer
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
      - net.ipv4.conf.all.src_valid_mark=1 # à confirmer
    restart: unless-stopped
```

In the log I have this message error : 

```
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
[2023-07-08T21:22:03+00:00] Finding the best server...
parse error: Invalid numeric literal at line 1, column 7
[2023-07-08T21:22:15+00:00] Unable to select a server ¯\_(⊙︿⊙)_/¯
```
So I have a container Jdownloader who access to internet under VPN NordVPN but it not function now
I have not change the conf since many month....

Does anyone could help me ?

Thanks
