### ISSUE TITLE
DNS no longer seems to work correctly after no changes to docker image

### ISSUE THREAD

**Issue by Jo-Dan** [bubuntux/nordlynx#160]
### **Describe the bug**
My containers behind the VPN don't seem to be able to resolve names (such as google.com) anymore. All of my healthchecks based on curling or pinging no longer work and the services themselves no longer work properly either due to network issues.
I have made absolutely no changes to the compose or any other part of my network or system.

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: '3.4'
services:
   vpn:
      container_name: vpn
      image: ghcr.io/bubuntux/nordlynx:latest
      security_opt:
        - label:disable
      restart: always
      dns:
      - 8.8.8.8
      - 4.4.4.4
      cap_add:
        - NET_ADMIN #required
      environment:
        - NETWORK=192.168.1.0/24  # So it can be accessed within the local
        - PRIVATE_KEY=__________ #required
        - QUERY=filters\[country_id\]=13
        - QUERY=filters\[servers_groups\]\[identifier\]=legacy_p2p
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      ports:
        - 8080:8080 # port for qbit web UI to be reachable from local network
        - 9117:9117
        - 6881:6881
        - 6881:6881/udp
        - 8989:8989
        - 7878:7878
        - 9696:9696
        - 6767:6767
        - 8686:8686
        - 38532:38532
        - 5656:5656
        #- 32400:32400
      volumes:
        - /dev/net:/dev/net:z # tun device
        - ${ROOT}/config/vpn:/config # OpenVPN configuration
      healthcheck:
        test: ["CMD-SHELL", "curl -f https://www.google.com || exit 1"]
        interval: 20s
        timeout: 10s
        retries: 3
        start_period: 10s
  ...
```

### **Expected behavior**
Hostnames resolve normally

### **Logs**
curl: (6) Could not resolve host: www.google.com

### **Additional context**
Distribution used, versions, architecture and any other context about the problem here.
