### ISSUE TITLE
I can't access any urls with the firefox docker-compose.yml presented in the README

### ISSUE THREAD

**Issue by antonio-victor** [bubuntux/nordlynx#165]
### **Describe the bug**
I can't access any urls with the firefox docker-compose.yml presented in the README. After a while, the firefox says 
The connection has timed out

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3.8"
services:
    nordlynx:
        image: ghcr.io/bubuntux/nordlynx
        hostname: nordlynx
        container_name: nordlynx
        ports:
            - "3000:3000" # port I want forwarded for the firefox container
            - "3001:3001" # port I want forwarded for the firefox container
        cap_add:
            - NET_ADMIN                             # required
            - SYS_MODULE                            # maybe
        environment:
            - PRIVATE_KEY=XPTO (Credentials hidden)               # required
            - QUERY=filters\[servers_groups\]\[identifier\]=legacy_p2p
            - NET_LOCAL=192.168.0.0/16
            - TZ=America/New_York
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1   # maybe
            - net.ipv4.conf.all.rp_filter=2        # maybe; set reverse path filter to loose mode
            - net.ipv6.conf.all.disable_ipv6=1     # disable ipv6; recommended if using ipv4 only
        
    firefox:
        image: lscr.io/linuxserver/firefox:latest
        # hostname: firefox                        # won't work when you do network_mode
        container_name: firefox
        restart: unless-stopped
        depends_on:
            - nordlynx
        network_mode: service:nordlynx
        # ports:                                   # won't work; you need to do this in the nordlynx VPN container 
        #     - "3000:3000"                        # won't work; you need to do this in the nordlynx VPN container  
        #     - "3001:3001"                        # won't work; you need to do this in the nordlynx VPN container
        volumes:
            - /path/to/config:/config
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        security_opt:
            - seccomp:unconfined
        shm_size: "1gb"
  ...
```

### **Expected behavior**
Connect to websites normally via Firefox at localhost:3000

### **Logs**
```
PS C:\Users\***\***\***\***> docker-compose up
[+] Running 2/2
 ✔ Container nordlynx  Recreated                                                                                   0.1s
 ✔ Container firefox   Recreated                                                                                   0.1s
Attaching to firefox, nordlynx
nordlynx  | [migrations] started
nordlynx  | [migrations] no migrations found
nordlynx  | [2024-03-30T20:44:00+00:00] Firewall is up, everything has to go through the vpn
nordlynx  | usermod: no changes
nordlynx  | ───────────────────────────────────────
nordlynx  |   _____ __ __ _____ _____ _____ _____
nordlynx  |  |     |  |  |   __|_   _|     |     |
nordlynx  |  |   --|  |  |__   | | | |  |  | | | |
nordlynx  |  |_____|_____|_____| |_| |_____|_|_|_|
nordlynx  |        _____ __ __ _ __    ____
nordlynx  |       | __  |  |  | |  |  |    \
nordlynx  |       | __ -|  |  | |  |__|  |  |
nordlynx  |       |_____|_____|_|_____|____/
nordlynx  |
nordlynx  |   Based on images from linuxserver.io
nordlynx  | ───────────────────────────────────────
nordlynx  |
nordlynx  | To support the app dev(s) visit:
nordlynx  | Bubuntux: https://github.com/sponsors/bubuntux
nordlynx  | WireGuard: https://www.wireguard.com/donations/
nordlynx  | To support LSIO projects visit:
nordlynx  | https://www.linuxserver.io/donate/
nordlynx  |
nordlynx  | ───────────────────────────────────────
nordlynx  | GID/UID
nordlynx  | ───────────────────────────────────────
nordlynx  |
nordlynx  | User UID:    911
nordlynx  | User GID:    911
nordlynx  | ───────────────────────────────────────
nordlynx  |
firefox   | [migrations] started
firefox   | [migrations] no migrations found
firefox   | ───────────────────────────────────────
firefox   |
firefox   |       ██╗     ███████╗██╗ ██████╗
firefox   |       ██║     ██╔════╝██║██╔═══██╗
firefox   |       ██║     ███████╗██║██║   ██║
firefox   |       ██║     ╚════██║██║██║   ██║
firefox   |       ███████╗███████║██║╚██████╔╝
firefox   |       ╚══════╝╚══════╝╚═╝ ╚═════╝
firefox   |
firefox   |    Brought to you by linuxserver.io
firefox   | ───────────────────────────────────────
firefox   |
firefox   | To support LSIO projects visit:
firefox   | https://www.linuxserver.io/donate/
firefox   |
firefox   | ───────────────────────────────────────
firefox   | GID/UID
firefox   | ───────────────────────────────────────
firefox   |
firefox   | User UID:    1000
firefox   | User GID:    1000
firefox   | ───────────────────────────────────────
firefox   |
firefox   | [custom-init] No custom files found, skipping...
firefox   | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
firefox   |
firefox   | Xvnc KasmVNC 1.2.0 - built Mar 23 2024 18:40:17
firefox   | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
firefox   | See http://kasmweb.com for information on KasmVNC.
firefox   | Underlying X server release 12014000, The X.Org Foundation
firefox   |
firefox   | [ls.io-init] done.
firefox   | The XKEYBOARD keymap compiler (xkbcomp) reports:
firefox   | > Warning:          Could not resolve keysym XF86CameraAccessEnable
firefox   | > Warning:          Could not resolve keysym XF86CameraAccessDisable
firefox   | > Warning:          Could not resolve keysym XF86CameraAccessToggle
firefox   | > Warning:          Could not resolve keysym XF86NextElement
firefox   | > Warning:          Could not resolve keysym XF86PreviousElement
firefox   | > Warning:          Could not resolve keysym XF86AutopilotEngageToggle
firefox   | > Warning:          Could not resolve keysym XF86MarkWaypoint
firefox   | > Warning:          Could not resolve keysym XF86Sos
firefox   | > Warning:          Could not resolve keysym XF86NavChart
firefox   | > Warning:          Could not resolve keysym XF86FishingChart
firefox   | > Warning:          Could not resolve keysym XF86SingleRangeRadar
firefox   | > Warning:          Could not resolve keysym XF86DualRangeRadar
firefox   | > Warning:          Could not resolve keysym XF86RadarOverlay
firefox   | > Warning:          Could not resolve keysym XF86TraditionalSonar
firefox   | > Warning:          Could not resolve keysym XF86ClearvuSonar
firefox   | > Warning:          Could not resolve keysym XF86SidevuSonar
firefox   | > Warning:          Could not resolve keysym XF86NavInfo
firefox   | Errors from xkbcomp are not fatal to the X server
firefox   | Obt-Message: Xinerama extension is not present on the server
firefox   | MESA: error: ZINK: vkEnumeratePhysicalDevices failed (VK_ERROR_INITIALIZATION_FAILED)
firefox   | MESA: error: ZINK: failed to choose pdev
firefox   | glx: failed to create drisw screen
firefox   | failed to load driver: zink
nordlynx  | [2024-03-30T16:44:00-04:00] Enabling connection to eth0 192.168.0.2/20
nordlynx  | [2024-03-30T16:44:00-04:00] Enabling connection to secure interfaces
nordlynx  | [2024-03-30T16:44:01-04:00] No interface network6 detected
nordlynx  | [2024-03-30T16:44:01-04:00] Enabling connection to network 192.168.0.0/16
nordlynx  | [custom-init] No custom files found, skipping...
nordlynx  | [ls.io-init] done.
nordlynx  | [2024-03-30T16:44:01-04:00] Finding the best server...
nordlynx  | [2024-03-30T16:44:01-04:00] Using server: {
nordlynx  |   "id": 977561,
nordlynx  |   "created_at": "2021-03-16 12:56:46",
nordlynx  |   "updated_at": "2024-03-30 20:41:42",
nordlynx  |   "name": "Brazil #87",
nordlynx  |   "station": "185.153.176.201",
nordlynx  |   "ipv6_station": "",
nordlynx  |   "hostname": "br87.nordvpn.com",
nordlynx  |   "load": 32,
nordlynx  |   "status": "online",
nordlynx  |   "type": "physical",
nordlynx  |   "cpt": 0,
nordlynx  |   "locations": [
nordlynx  |     {
nordlynx  |       "id": 4079,
nordlynx  |       "created_at": "2022-03-24 07:13:39",
nordlynx  |       "updated_at": "2022-03-24 07:13:39",
nordlynx  |       "latitude": -23.533333,
nordlynx  |       "longitude": -46.616667,
nordlynx  |       "country": {
nordlynx  |         "id": 30,
nordlynx  |         "name": "Brazil",
nordlynx  |         "code": "BR",
nordlynx  |         "city": {
nordlynx  |           "id": 890249,
nordlynx  |           "name": "Sao Paulo",
nordlynx  |           "latitude": -23.533333,
nordlynx  |           "longitude": -46.616667,
nordlynx  |           "dns_name": "sao-paulo",
nordlynx  |           "hub_score": 0
nordlynx  |         }
nordlynx  |       }
nordlynx  |     }
nordlynx  |   ],
nordlynx  |   "groups": [
nordlynx  |     {
nordlynx  |       "id": 11,
nordlynx  |       "created_at": "2017-06-13 13:43:00",
nordlynx  |       "updated_at": "2017-06-13 13:43:00",
nordlynx  |       "title": "Standard VPN servers",
nordlynx  |       "identifier": "legacy_standard",
nordlynx  |       "type": {
nordlynx  |         "id": 3,
nordlynx  |         "created_at": "2017-06-13 13:40:17",
nordlynx  |         "updated_at": "2017-06-13 13:40:23",
nordlynx  |         "title": "Legacy category",
nordlynx  |         "identifier": "legacy_group_category"
nordlynx  |       }
nordlynx  |     },
nordlynx  |     {
nordlynx  |       "id": 15,
nordlynx  |       "created_at": "2017-06-13 13:43:38",
nordlynx  |       "updated_at": "2017-06-13 13:43:38",
nordlynx  |       "title": "P2P",
nordlynx  |       "identifier": "legacy_p2p",
nordlynx  |       "type": {
nordlynx  |         "id": 3,
nordlynx  |         "created_at": "2017-06-13 13:40:17",
nordlynx  |         "updated_at": "2017-06-13 13:40:23",
nordlynx  |         "title": "Legacy category",
nordlynx  |         "identifier": "legacy_group_category"
nordlynx  |       }
nordlynx  |     },
nordlynx  |     {
nordlynx  |       "id": 21,
nordlynx  |       "created_at": "2017-10-27 14:23:03",
nordlynx  |       "updated_at": "2017-10-30 08:09:48",
nordlynx  |       "title": "The Americas",
nordlynx  |       "identifier": "the_americas",
nordlynx  |       "type": {
nordlynx  |         "id": 5,
nordlynx  |         "created_at": "2017-10-27 14:16:30",
nordlynx  |         "updated_at": "2017-10-27 14:16:30",
nordlynx  |         "title": "Regions",
nordlynx  |         "identifier": "regions"
nordlynx  |       }
nordlynx  |     }
nordlynx  |   ],
nordlynx  |   "specifications": [
nordlynx  |     {
nordlynx  |       "id": 8,
nordlynx  |       "title": "Version",
nordlynx  |       "identifier": "version",
nordlynx  |       "values": [
nordlynx  |         {
nordlynx  |           "id": 257,
nordlynx  |           "value": "2.1.0"
nordlynx  |         }
nordlynx  |       ]
nordlynx  |     }
nordlynx  |   ],
nordlynx  |   "ips": [
nordlynx  |     {
nordlynx  |       "id": 275810,
nordlynx  |       "created_at": "2021-03-17 12:06:42",
nordlynx  |       "updated_at": "2021-03-17 12:06:42",
nordlynx  |       "server_id": 977561,
nordlynx  |       "ip_id": 190886,
nordlynx  |       "type": "entry",
nordlynx  |       "ip": {
nordlynx  |         "id": 190886,
nordlynx  |         "ip": "185.153.176.201",
nordlynx  |         "version": 4
nordlynx  |       }
nordlynx  |     }
nordlynx  |   ]
nordlynx  | }
nordlynx  | [2024-03-30T16:44:01-04:00] Connecting...
nordlynx  | [#]
nordlynx  | [#] ip link add wg0 type wireguard
nordlynx  | [#] wg setconf wg0 /dev/fd/63
nordlynx  | [#] ip -4 address add 10.5.0.2/32 dev wg0
nordlynx  | [#] ip link set mtu 1420 up dev wg0
nordlynx  | [#] resolvconf -a wg0 -m 0 -x
nordlynx  | [#] wg set wg0 fwmark 51820
nordlynx  | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
nordlynx  | [#] ip -4 rule add not fwmark 51820 table 51820
nordlynx  | [#] ip -4 rule add table main suppress_prefixlength 0
nordlynx  | [#] iptables-restore -n
nordlynx  | Warning: Extension CONNMARK revision 0 not supported, missing kernel module?
nordlynx  | iptables-restore: line 7 failed
nordlynx  | [#] resolvconf -d wg0 -f
nordlynx  | [#] ip -4 rule delete table 51820
nordlynx  | [#] ip -4 rule delete table main suppress_prefixlength 0
nordlynx  | [#] ip link delete dev wg0
nordlynx  | [2024-03-30T16:44:01-04:00] Connected! \(ᵔᵕᵔ)/
firefox   |  2024-03-30 16:44:13,132 [INFO] websocket 0: got client connection from 127.0.0.1
firefox   |  2024-03-30 16:44:13,140 [PRIO] Connections: accepted: @192.168.0.1_1711831453.132648::websocket
```
