### ISSUE TITLE
api.nordvpn.com not found

### ISSUE THREAD

**Issue by julio8a** [bubuntux/nordlynx#180]
### **Describe the bug**
Seems that the API can no longer be found. I keep getting a message and it tries every 5 seconds. 

Was working fine before for over a year. I also got a new Private_Key following the instructions from the README.

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)

```
version: "3"
services:
  nordvpn:
    image: ghcr.io/bubuntux/nordlynx:latest
    container_name: nordvpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
#    sysctls:
#      - net.ipv4.conf.all.rp_filter=2
    environment:
      - PRIVATE_KEY=[REDACTED]
      - NET_LOCAL=192.168.86.0/24
      - TZ=America/Los_Angeles      
      - QUERY=filters\[identifier\]=legacy_p2p
    ports:
      - 8080:8080 # qbittorrent web interface
      - 6881:6881 # Deluge and qbittorrent P2P
      - 6881:6881/udp # Deluge and qbittorrent P2P
    restart: unless-stopped
```

Error I get on loop: 
```
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
```

### **Expected behavior**
Connect to nordvpn and run the service. 

### **Logs**
```
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
Seems like we have no internet connection. Retrying in 5 seconds...
ip6tables v1.8.10 (nf_tables): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.

```

### **Additional context**
Running on a raspberry Pi
