### ISSUE TITLE
Connected but unhealthy

### ISSUE THREAD

**Issue by godfuture** [bubuntux/nordlynx#186]
### **Describe the bug**
Docker container is deployed and started correctly showing green status "healthy". Connection is up and running. All seems ok. After some time (mostly after some days, last issue appeared after 6 days) health goes to yellow "unhealthy". No traffic is going through the tunnel anymore. A restart of docker container solves the issue for next couple of days. This issue was not existant two years ago. It started some time in 2024 or end of 2023.

### **To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run ... bubuntux/nordlynx `

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: '3'
services:
  nordvpnlynx:
      image: ghcr.io/bubuntux/nordlynx:latest
      container_name: "nordvpnlynx"
      network_mode: bridge
      restart: always
      ports:
        - 8990:17442/tcp
        - 8991:8081/tcp
        - 8410:8000/tcp  
        - 8420:7227/tcp
        - 8421:7228/tcp
        - 8430:9666/tcp
        - 8080:8080/tcp      
        - 1080:1080/tcp
        - 1080:1080/udp      
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        - PRIVATE_KEY=myPrivateKey
        - PERSISTENT_KEEP_ALIVE=25
        - NET_LOCAL=192.168.10.0/24
        - QUERY=filters\[country_id\]=153
        - DNS=192.168.10.2
        - TZ=Europe/Berlin
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /lib/modules:/lib/modules:ro
        - temp:/tmp
        - scripts:/var/local/scripts
      sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
      logging:
        driver: "fluentd"
        options:
          fluentd-address: ${FLUENTD_ADDRESS}
          tag: ${FLUENTD_TAG}
```

### **Expected behavior**
Once docker container is started up and health state shows "healthy" then container should not get in degraded state after some time. 

### **Logs**
In logs I can only see normal logs, even the interruption happed. The last line in "unhealthy" state is:
[2025-01-22T13:10:30+01:00] Connected! \(ᵔᵕᵔ)/

### **Additional context**
Using docker image "sha256:36e1abca987d315770c9703d40e90a6eee3e73e4e06a2c076870a381ec93c7d3". Debian 12. Kernel Linux 6.1.0-28-amd64.
