### ISSUE TITLE
IPTABLES does not consider interface when adding docker_networks to allow list.

### ISSUE THREAD

**Issue by Trakkasure** [bubuntux/nordlynx#19]
### **Describe the bug**
When a docker container has more than one network, multiple interfaces are created within the container. The 03-inet script adds these networks, but does not consider that they are on different interfaces. This causes all networks on interfaces NOT on eth0 to fail. This happens for both INPUT and OUTPUT chains. This has been validated by manually adding the iptable entries for networks on the eth1 interface.

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: "3"
services:
  nordvpn:
    container_name: nordvpn
    hostname: nordvpn
    image: ghcr.io/bubuntux/nordlynx:latest
    cap_add:
      - NET_ADMIN
    sysctls:
      - "net.ipv4.conf.all.src_valid_mark=1"
      - "net.ipv6.conf.all.disable_ipv6=1"
    environment:
      - "PRIVATE_KEY=####"
      - "ALLOWED_IPS=0.0.0.0/1" # portainer needed this
      - "NET_LOCAL=192.168.0.0/24,172.19.0.0/24" # MACVlan,ProxyNetwork
    mem_limit: "256m"
    memswap_limit: "256m"
    networks:
      vpn:  # bridge with /30 to allow nordlynx access to internet to establish VPN link
      Proxy: # with static address, I can route containers on a proxy network through me as a default route
        ipv4_address: 172.19.0.2
    restart: unless-stopped
networks:
  vpn:
    external: true
  Proxy:
    external: true
```

### **Expected behavior**
From nordlynx container, I should be able to ping any Proxy IP address. Since proxy is 2nd, it is eth1 interface within the container.
