### ISSUE TITLE
Performance slow compared to windows client running on host

### ISSUE THREAD

**Issue by markphillips100** [bubuntux/nordlynx#20]
I have successfully used a docker compose for a VPN using this image, along with a firefox image so I may access a speedtest.  The problem is I'm seeing at least a 20Mbps download speed drop compared to using a windows 10 VPN client (using nordlynx protocol) on the host computer.  

I have a 100Mbps ISP connection, and I'm running docker for desktop and WSL2 integration with an Ubuntu 20.04 distro.  I use a modified (by me) WSL2 kernel to support the `CONFIG_NETFILTER_XT_MATCH_CONNMARK=y` setting which is needed to allow the wireguard setup to work.

I've run the following tests using browsers to speedtest:
|VPN|Scenario|Download speed|
|-----|---------|----------|
|None|Win 10 browser|100Mbps|
|Win10 Nordlynx VPN|Win 10 browser|95Mbps|
|None|Firefox container browser configured with bridge networking to the host|95Mbps|
|Win10 Nordlynx VPN|Firefox container browser configured with bridge networking to the host|95Mbps|
|Linux Docker Nordlynx VPN|Firefox container browser using Nordlynx container network|70Mbps|

Note: Upload speeds are always about 35Mbps for all tests.

### **To Reproduce using docker-compose**
```
version: '3'
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=<redacted>         # Required
      - QUERY=filters\[country_id\]=13 # 227 UK, 13 AUS
      - NET_LOCAL=192.168.0.0/24  # So it can be accessed within the local network
    ports:
      - 8080:8080
      - 3000:3000
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1```

  firefox:
    image: ghcr.io/linuxserver/firefox
    environment:
      TZ: Australia/Brisbane
      PUID: 1000 # set to UID of your user
      PGID: 1000 # set to GID of your user
    volumes:
      - "./config/firefox:/config" # config directory
    network_mode: service:vpn
    shm_size: "1gb"
    restart: unless-stopped
    depends_on:
      - vpn

  # To run a firefox container without going via the nordlynx container vpn
  # comment the above firefox config and uncomment the section below. Note: the port here is 3001 to not clash.
  # firefox:
  #   image: ghcr.io/linuxserver/firefox
  #   ports:
  #     - "3001:3000" # port mapping
  #   environment:
  #     TZ: Australia/Brisbane
  #     PUID: 1000 # set to UID of your user
  #     PGID: 1000 # set to GID of your user
  #   volumes:
  #     - "./config/firefox:/config" # config directory
  #   shm_size: "1gb"
  #   restart: unless-stopped

```

### **Expected behavior**
I expected the download speed to be much the same as for my windows 10 desktops (tried on two machines and both are 95Mbps+), and also what I obtain from the firefox container when using bridge networking to the host.

I also tried the original nordvpn image using regular user/pass credentials (no MFA enabled) and get the same test results.

### **Logs**
No errors appear in the docker compose log output.  Everything appears to be running.  Well, it is running after all.
