### ISSUE TITLE
Error at Startup: Unable to access interface: No such device

### ISSUE THREAD

**Issue by WINOFFRG** [bubuntux/nordlynx#23]
### **Describe the bug**
Faced issue while starting up the container. Got `unable to access interface: No such device` error

### **To Reproduce using docker CLI**
`docker run -d --cap-add=NET_ADMIN -e PRIVATE_KEY=xxxx ghcr.io/bubuntux/nordlynx`

### **To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=xxxx #required
    ports:
      - "8080:8080"
  web:
    build: /nodejs
    command: npm run start
    volumes:
        - .:/nodejs/
        - /nodejs/node_modules
    network_mode: service:nordlynx
    depends_on:
        - nordlynx
```

### **Expected behavior**
Exptected VPN Container to start normally.

### **Logs**
Logs from Docker Container
![image](https://user-images.githubusercontent.com/61311751/151695948-b1e48444-73c7-4099-a639-608c7cbc741a.png)

**Comment by WINOFFRG** [comment]
Issue 2: I tried the same thing on my Ubuntu Server. The case seems a bit different there. There the VPN gets connected properly but the issue is same as with `nordvpn` repository. The host name is not resolved.

Here are the logs below:

```
Attaching to dockernordvpn_nordlynx_1, dockernordvpn_web_1
nordlynx_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
nordlynx_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
nordlynx_1  | [fix-attrs.d] applying ownership & permissions fixes...
nordlynx_1  | [fix-attrs.d] done.
nordlynx_1  | [cont-init.d] executing container initialization scripts...
nordlynx_1  | [cont-init.d] 00-firewall: executing... 
nordlynx_1  | Firewall is up, everything has to go through the vpn
nordlynx_1  | [cont-init.d] 00-firewall: exited 0.
nordlynx_1  | [cont-init.d] 10-validate: executing... 
nordlynx_1  | Wireguard module is active
nordlynx_1  | [cont-init.d] 10-validate: exited 0.
nordlynx_1  | [cont-init.d] 20-inet: executing... 
nordlynx_1  | Enabling connection to secure interface and docker network
nordlynx_1  | [cont-init.d] 20-inet: exited 0.
nordlynx_1  | [cont-init.d] 20-inet6: executing... 
nordlynx_1  | No inet6 network
nordlynx_1  | [cont-init.d] 20-inet6: exited 0.
nordlynx_1  | [cont-init.d] 30-route: executing... 
nordlynx_1  | [cont-init.d] 30-route: exited 0.
nordlynx_1  | [cont-init.d] 30-route6: executing... 
nordlynx_1  | [cont-init.d] 30-route6: exited 0.
nordlynx_1  | [cont-init.d] 40-allowlist: executing... 
nordlynx_1  | [cont-init.d] 40-allowlist: exited 0.
nordlynx_1  | [cont-init.d] done.
nordlynx_1  | [services.d] starting services
nordlynx_1  | [services.d] done.
web_1       | 
web_1       | > docker_web_app@1.0.0 start
web_1       | > node server.js
web_1       | 
web_1       | Running on http://127.0.0.1:8080
nordlynx_1  | [#] 
nordlynx_1  | [#] ip link add wg0 type wireguard
nordlynx_1  | [#] wg setconf wg0 /dev/fd/63
nordlynx_1  | [#] ip -4 address add 10.5.0.2/32 dev wg0
nordlynx_1  | [#] ip link set mtu 1420 up dev wg0
nordlynx_1  | [#] resolvconf -a wg0 -m 0 -x
nordlynx_1  | [#] wg set wg0 fwmark 51820
nordlynx_1  | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
nordlynx_1  | [#] ip -4 rule add not fwmark 51820 table 51820
nordlynx_1  | [#] ip -4 rule add table main suppress_prefixlength 0
nordlynx_1  | [#] iptables-restore -n
nordlynx_1  | [#] 
nordlynx_1  | interface: wg0
nordlynx_1  |   public key: abPcLNV7slzqaoFMG+ZcYRdbKxkLp74kWQaEvfiFU18=
nordlynx_1  |   private key: (hidden)
nordlynx_1  |   listening port: 51820
nordlynx_1  |   fwmark: 0xca6c
nordlynx_1  | 
nordlynx_1  | peer: +7eydqFtf+DGlXeHLneRqoD2zMR8gGr3hgCq89wA9Qg=
nordlynx_1  |   endpoint: 185.203.122.118:51820
nordlynx_1  |   allowed ips: 0.0.0.0/0
nordlynx_1  |   transfer: 0 B received, 148 B sent
nordlynx_1  |   persistent keepalive: every 25 seconds
```

@bubuntux Can you please take a look at this, need your help on this!

**Comment by bubuntux** [comment]
for issue 2, seems to be connecting just fine to the nordvpn server, if the host does not resolve that means a dns issue

 The other one not sure, probably some host specific issue

**Comment by MervisDiamonds** [comment]
I have a similar setup on my QNAP: 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-firewall: executing... 
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 10-validate: executing... 
Wireguard module is active
[cont-init.d] 10-validate: exited 0.
[cont-init.d] 20-inet: executing... 
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing... 
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing... 
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing... 
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing... 
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'raw'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
[#] resolvconf -d wg0 -f
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg0
Unable to access interface: No such device`

**Comment by bubuntux** [comment]
try adding  cap-add=NET_ADMIN,NET_RAW

**Comment by MervisDiamonds** [comment]
Working!  I had to enable the wireguard server on my QNAP.

**Comment by lustyffh** [comment]
Hi, i'm also having similar issue but my log output is somewhat different. The host is on Ubuntu 21.10
Seems like startup script doesn't initiate wireguard services at all.

I use the following docker-compose:

```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    restart: unless-stopped
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                
      - PRIVATE_KEY=[key]
      - NET_LOCAL=192.168.0.0/16
      - ALLOWED_IPS=0.0.0.0/0
    ports:
      - 8120:8118
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  privoxy:
   image: splazit/privoxy-alpine
   restart: unless-stopped
   network_mode: service:vpn
   depends_on:
    - vpn
```


```
Recreating bubuntux-nordlynx_vpn_1 ... done
Recreating bubuntux-nordlynx_privoxy_1 ... done
Attaching to bubuntux-nordlynx_vpn_1, bubuntux-nordlynx_privoxy_1
privoxy_1  | 2022-02-26 19:49:39.657 7f0b01496b48 Info: Privoxy version 3.0.31
privoxy_1  | 2022-02-26 19:49:39.657 7f0b01496b48 Info: Program name: privoxy
vpn_1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
vpn_1      | [s6-init] ensuring user provided files have correct perms...exited 0.
vpn_1      | [fix-attrs.d] applying ownership & permissions fixes...
vpn_1      | [fix-attrs.d] done.
vpn_1      | [cont-init.d] executing container initialization scripts...
vpn_1      | [cont-init.d] 00-firewall: executing... 
vpn_1      | Firewall is up, everything has to go through the vpn
vpn_1      | [cont-init.d] 00-firewall: exited 0.
vpn_1      | [cont-init.d] 10-validate: executing... 
vpn_1      | Wireguard module is active
vpn_1      | [cont-init.d] 10-validate: exited 0.
vpn_1      | [cont-init.d] 20-inet: executing... 
vpn_1      | Enabling connection to secure interface and docker network
vpn_1      | [cont-init.d] 20-inet: exited 0.
vpn_1      | [cont-init.d] 20-inet6: executing... 
vpn_1      | No inet6 network
vpn_1      | [cont-init.d] 20-inet6: exited 0.
vpn_1      | [cont-init.d] 30-route: executing... 
vpn_1      | Enabling connection to network 192.168.0.0/16
vpn_1      | [cont-init.d] 30-route: exited 0.
vpn_1      | [cont-init.d] 30-route6: executing... 
vpn_1      | [cont-init.d] 30-route6: exited 0.
vpn_1      | [cont-init.d] 40-allowlist: executing... 
vpn_1      | [cont-init.d] 40-allowlist: exited 0.
vpn_1      | [cont-init.d] done.
vpn_1      | [services.d] starting services
vpn_1      | [services.d] done.
```
