### ISSUE TITLE
Unable to connect running in Kubernetes

### ISSUE THREAD

**Issue by IvanBrazza** [bubuntux/nordlynx#3]
### Consider creating a thread in the discussion section, specially if you don't know what the problem is or is not directly related to the image itself.

**Describe the bug**
The container doesn’t connect to the VPN on startup. It fails at the [20-inet step](https://github.com/bubuntux/nordlynx/blob/main/rootfs/etc/cont-init.d/20-inet) that it isn’t able to reach api.nordvpn.com. Running in a Kubernetes environment.

**To Reproduce using docker CLI**
Full command needs to be provided (hide credentials)
`docker run ... bubuntux/nordlynx `

Using Kubernetes, not Docker, no CLI to provide.

**To Reproduce using docker-compose**
docker-compose.yml if used  (hide credentials)
```
version: '3'
services:
  vpn:
    image: bubuntux/nordlynx
  ...
```

Using Kubernetes, not Docker, Kubernetes pod configuration:

```

       - name: nordvpn
         image: ghcr.io/bubuntux/nordlynx:latest
         securityContext:
           privileged: true
           capabilities:
             add: 
             - "NET_ADMIN"
             - "SYS_MODULE"
         env:
         - name: PRIVATE_KEY
           valueFrom:
             secretKeyRef:
               name: jackett
               key: NORDVPN_PRIVKEY
         - name: NET_LOCAL
           value: "10.0.0.0/8"
```

**Expected behavior**
A clear and concise description of what you expected to happen and a simple way for someone else to test it.

The VPN should connect.

**Logs**
Focus on errors or warnings messages, if not available post entire logs

```
[s6-init[] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init[] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d[] applying ownership & permissions fixes...
[fix-attrs.d[] done.
[cont-init.d[] executing container initialization scripts...
[cont-init.d[] 00-firewall: executing... 
Firewall is up, everything has to go through the vpn
[cont-init.d[] 00-firewall: exited 0.
[cont-init.d[] 10-module: executing... 
Uname info: Linux jackett-844bc9f6c5-785ww 5.8.0-0.bpo.2-amd64 #1 SMP Debian 5.8.10-1~bpo10+1 (2020-09-26) x86_64 x86_64 x86_64 GNU/Linux
Wireguard module is active
[cont-init.d[] 10-module: exited 0.
[cont-init.d[] 20-inet: executing... 
Enabling connection to secure interface and docker network
iptables v1.8.4 (legacy): host/network `api.nordvpn.com' not found
Try `iptables -h' or 'iptables --help' for more information.
[cont-init.d[] 20-inet: exited 0.
[cont-init.d[] 20-inet6: executing... 
Enabling connection to secure interface6 and docker network6
ip6tables v1.8.4 (legacy): host/network `api.nordvpn.com' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.
[cont-init.d[] 20-inet6: exited 0.
[cont-init.d[] 30-route: executing... 
Enabling connection to network 10.0.0.0/8
[cont-init.d[] 30-route: exited 0.
[cont-init.d[] 30-route6: executing... 
[cont-init.d[] 30-route6: exited 0.
[cont-init.d[] 40-allowlist: executing... 
[cont-init.d[] 40-allowlist: exited 0.
[cont-init.d[] done.
[services.d[] starting services
[services.d[] done.
[#[] 
[#[] ip link add wg0 type wireguard
[#[] wg setconf wg0 /dev/fd/63
Line unrecognized: `PublicKey='
Configuration parsing error
[#[] ip link delete dev wg0
Unable to access interface: No such device
```

**Additional context**
Distribution used, versions, architecture and any other context about the problem here.

It seems it's struggling to reach the outside network properly - within the container I can access other services in the Kubernetes network, but not anything on the internet. It's able to resolve DNS, but making connections just times out:

```
root@jackett-77bd79ff8b-t5fkz:/# curl https://api.nordvpn.com/ -v
*   Trying 104.17.50.74:443...
* TCP_NODELAY set
* connect to 104.17.50.74 port 443 failed: Connection timed out
```
