### ISSUE TITLE
Connected to NordVPN on GKE but cannot reach other nodes

### ISSUE THREAD

**Issue by tab1293** [bubuntux/nordlynx#5]
**Describe the bug**
I am able to successfully connect to NordVPN but once connected the containers running in the pod can not reach other expected nodes. DNS is not resolving and containers can not connect to nodes on the internet.

**K8S config**
```
apiVersion: v1
kind: Pod
metadata:
  name: nordlynx-k8s
  labels:
    app: nordlynx-k8s
spec:
  containers:
    - name: nordlynx
      image: ghcr.io/bubuntux/nordlynx:latest
      env:
        - name: PRIVATE_KEY
          value: priv-key
      securityContext:
        privileged: true
        capabilities:
          add:
            - "NET_ADMIN"
    - image: alpine:latest
      command:
        - /bin/sh
        - -c
        - "sleep 3600"
      imagePullPolicy: Always
      name: alpine
```

**Expected behavior**
Expected to be able to connect to public nodes on the internet after VPN connection is established. This was working as expected on the older image here: https://github.com/bubuntux/nordvpn

**nordlynx container logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-firewall: executing... 
Firewall is up, everything has to go through the vpn
[cont-init.d] 00-firewall: exited 0.
[cont-init.d] 10-validate: executing... 
Wireguard module is active
[cont-init.d] 10-validate: exited 0.
[cont-init.d] 20-inet: executing... 
Enabling connection to secure interface and docker network
[cont-init.d] 20-inet: exited 0.
[cont-init.d] 20-inet6: executing... 
No inet6 network
[cont-init.d] 20-inet6: exited 0.
[cont-init.d] 30-route: executing... 
[cont-init.d] 30-route: exited 0.
[cont-init.d] 30-route6: executing... 
[cont-init.d] 30-route6: exited 0.
[cont-init.d] 40-allowlist: executing... 
[cont-init.d] 40-allowlist: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.5.0.2/32 dev wg0
[#] ip link set mtu 1380 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] iptables-restore -n
[#] 
interface: wg0
  public key: 89ssiAR8Jc29v66RDwtvOJWNE+c/fJ5xMZ/XFO5aS2w=
  private key: (hidden)
  listening port: 51820
  fwmark: 0xca6c

peer: vR4DQPU577hI6PbjxmUkhlAEXIGISzmlvr9yqQs5uGc=
  endpoint: 23.105.173.223:51820
  allowed ips: 0.0.0.0/0
  latest handshake: Now
  transfer: 92 B received, 180 B sent
  persistent keepalive: every 25 seconds
```

**Debug commands within nordlynx container**
```
bash-5.1# wg
interface: wg0
  public key: 89ssiAR8Jc29v66RDwtvOJWNE+c/fJ5xMZ/XFO5aS2w=
  private key: (hidden)
  listening port: 51820
  fwmark: 0xca6c

peer: vR4DQPU577hI6PbjxmUkhlAEXIGISzmlvr9yqQs5uGc=
  endpoint: 23.105.173.223:51820
  allowed ips: 0.0.0.0/0
  latest handshake: 18 seconds ago
  transfer: 92 B received, 180 B sent
  persistent keepalive: every 25 seconds
bash-5.1# ifconfig
eth0      Link encap:Ethernet  HWaddr FE:ED:31:D4:32:EE  
          inet addr:10.88.8.30  Bcast:10.88.8.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:63 errors:0 dropped:0 overruns:0 frame:0
          TX packets:65 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:16144 (15.7 KiB)  TX bytes:6134 (5.9 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wg0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.5.0.2  P-t-P:10.5.0.2  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP  MTU:1380  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:92 (92.0 B)  TX bytes:308 (308.0 B)

bash-5.1# iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 10.88.8.0/24 -i eth0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -d 10.88.8.0/24 -i eth0 -j ACCEPT
-A FORWARD -s 10.88.8.0/24 -i eth0 -j ACCEPT
-A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o wg+ -j ACCEPT
-A OUTPUT -d 10.88.8.0/24 -o eth0 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 53 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
-A OUTPUT -d 104.17.50.74/32 -o eth0 -p tcp -m tcp --dport 443 -j ACCEPT
-A OUTPUT -d 104.17.49.74/32 -o eth0 -p tcp -m tcp --dport 443 -j ACCEPT

bash-5.1# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.88.8.1       0.0.0.0         UG    0      0        0 eth0
10.88.8.0       10.88.8.1       255.255.255.0   UG    0      0        0 eth0
10.88.8.1       0.0.0.0         255.255.255.255 UH    0      0        0 eth0

bash-5.1# nslookup google.com
;; connection timed out; no servers could be reached

bash-5.1#  ping  142.250.81.23 (google.com ip address)
PING 142.250.81.23 (142.250.81.23): 56 data bytes
^C
--- 142.250.81.23 ping statistics ---
8 packets transmitted, 0 packets received, 100% packet loss

bash-5.1# ping 10.88.1.167 (other pod in the kubernetes cluster)
PING 10.88.1.167 (10.88.1.167): 56 data bytes
^C
--- 10.88.1.167 ping statistics ---
8 packets transmitted, 0 packets received, 100% packet loss

```

**Additional context**
I had this working correctly in the same exact GKE environment using the older nordvpn image with the k8s config posted here: https://github.com/bubuntux/nordvpn/issues/283

Maybe I am missing some simple configuration in the new image to get things working? Any help would be appreciated!

**Comment by tab1293** [comment]
I was able to get it working now. I needed these two sysctl flags: 
```
net.ipv6.conf.all.disable_ipv6=1 
net.ipv4.conf.all.src_valid_mark=1
``` 
Here is my working k8s config for anyone else who might be having a hard time running on GKE
```
apiVersion: v1
kind: Pod
metadata:
  name: nordlynx-k8s
  labels:
    app: nordlynx-k8s
spec:
  initContainers:
    - name: init-sysctl
      image: busybox
      command: ["/bin/sh"]
      args:
        - -c
        - >-
            sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&
            sysctl -w net.ipv4.conf.all.src_valid_mark=1
      securityContext:
        privileged: true
  containers:
    - name: nordvpn
      image: ghcr.io/bubuntux/nordlynx:latest
      env:
        - name: PRIVATE_KEY
          value: priv-key
      securityContext:
        capabilities:
          add:
            - "NET_ADMIN"
    - image: alpine:latest
      command:
        - /bin/sh
        - -c
        - "sleep 3600"
      imagePullPolicy: Always
      name: alpine
```
