### ISSUE TITLE
Running on swarm

### ISSUE THREAD

**Issue by kolonuk** [bubuntux/nordlynx#58]
### **Describe the bug**
I have a Docker swarm with 3 nodes (Ras Pi 4's), and trying to get a the vpn running.  It's brand new, fresh OS install and updates applied. No extra features installed other than Portainer.

However, when deployed on the swarm, the container continually restarts, stating it is unable to select a server - see logs below.

There is a restart delay to prevent hammering NordVPN and getting locked out, so that isn't the issue.

### **To Reproduce using docker CLI**
Only relevant on Docker swarm:
`docker stack deploy --compose-file docker-compose.yml vpnstack `

### **To Reproduce using docker-compose**
```
version: "3"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY=xxxx
      - NET_LOCAL=192.168.33.0/24
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        delay: 5m
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

### **Expected behavior**
I was expecting the container to be created and usable on the swarm.  It works using the workaround (see below), which is effectively standalone mode.

### **Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 00-firewall: executing... ,
[2022-03-16T10:40:44+00:00] Firewall is up, everything has to go through the vpn,
[cont-init.d] 00-firewall: exited 0.,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 01-migrations: executing... ,
[migrations] started,
[migrations] no migrations found,
[cont-init.d] 01-migrations: exited 0.,
[cont-init.d] 02-tamper-check: executing... ,
[cont-init.d] 02-tamper-check: exited 0.,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support the app dev(s) visit:,
Bubuntux: https://github.com/sponsors/bubuntux,
WireGuard: https://www.wireguard.com/donations/,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    911,
User gid:    911,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 10-validate: executing... ,
[cont-init.d] 10-validate: exited 0.,
[cont-init.d] 20-inet: executing... ,
[2022-03-16T10:40:44+00:00] Enabling connection to eth0 10.0.5.6/24,
[2022-03-16T10:40:44+00:00] Enabling connection to eth1 172.18.0.3/16,
[2022-03-16T10:40:44+00:00] Enabling connection to secure interfaces,
iptables v1.8.7 (legacy): host/network `api.nordvpn.com' not found,
Try `iptables -h' or 'iptables --help' for more information.,
[cont-init.d] 20-inet: exited 2.,
[cont-init.d] 20-inet6: executing... ,
[2022-03-16T10:40:49+00:00] No interface network6 detected,
[cont-init.d] 20-inet6: exited 0.,
[cont-init.d] 30-route: executing... ,
[2022-03-16T10:40:49+00:00] Enabling connection to network 192.168.33.0/24,
RTNETLINK answers: Network unreachable,
[cont-init.d] 30-route: exited 0.,
[cont-init.d] 30-route6: executing... ,
[cont-init.d] 30-route6: exited 0.,
[cont-init.d] 40-allowlist: executing... ,
[cont-init.d] 40-allowlist: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2022-03-16T10:40:49+00:00] Finding the best server...,
curl: (6) Could not resolve host: api.nordvpn.com,
curl: (6) Could not resolve host: api.nordvpn.com,
curl: (6) Could not resolve host: api.nordvpn.com,
curl: (6) Could not resolve host: api.nordvpn.com,
[2022-03-16T10:41:16+00:00] Unable to select a server ¯\_(⊙︿⊙)_/¯,
[2022-03-16T10:42:16+00:00] Connection summary:,
Unable to access interface: No such device,
wg-quick: `/etc/wireguard/wg0.conf' does not exist,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.
```

### **Additional context**
Raspberry Pi 4 8Gb
```
pi@worker2:~ $ hostnamectl
   Static hostname: worker2
         Icon name: computer
        Machine ID: 3576b14564f940cd917fe0f11033318b
           Boot ID: 8eef927a78104973a4a432527dc12a8a
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.103-v8+
      Architecture: arm64
```

### **Workaround***
Instead, I created a Docker in Docker container globally deployed which creates a VPN on each node which can be used locally.  It works, but downside is it creates as many VPNs as nodes!

```
version: "3.3"
services:
  nordlynxcontroller:
    image: docker
    command: |
      sh -c "
        docker run --cap-add=NET_ADMIN -e PRIVATE_KEY=xxx -e NET_LOCAL=192.168.33.0/24 --sysctl net.ipv6.conf.all.disable_ipv6=1 --name nordlynx ghcr.io/bubuntux/nordlynx "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        delay: 1m
```

### ** FYI ***
I am going to try creating a special Docker swarm network and a single VPN - a bit out of my knowledge zone right now, so not sure how or if it will work - help appreciated!

**Comment by gmalenko** [comment]
@kolonuk  did you ever find a solution (besides the workaround)?  I'm running this on docker swarm too and have ran into this.

**Comment by gbozzetti** [comment]
Please don't close this issue, I have the same problem!

**Comment by jorgeadeviam1994** [comment]
No cierres este tema, tengo el mismo problema!

**Comment by GadgetGeekNI** [comment]
Any update on this?

This is the only thing holding me back from implementing swarm.

**Comment by kolonuk** [comment]
An update - I gave up and went with kubernetes. The networking in swarm is beyond me, but I kinda understand kubernetes. I used a mixture of this https://medium.com/@gallaghersam95/experiment-k8s-pod-as-an-internet-egress-network-appliance-5a0a29d7c9dd and other guides. Sorted!

**Comment by michaelkrieger** [comment]
Got this working by adding "INTERFACE=eth1" as a parameter.  This is a working config in swarm:

```
  nordlynx:
    container_name: nordlynx
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # docker run --rm --cap-add=NET_ADMIN -e USER=... -e PASS='...' bubuntux/nordvpn:get_private_key
      - PRIVATE_KEY=...
      - NET_LOCAL=192.168.0.0/24
      - INTERFACE=eth1
      - TZ=America/Toronto
      - "DNS=1.1.1.1,8.8.8.8" # Cloudflare with Google backup
      # QUERY NordVPN API Cheat Sheet: https://sleeplessbeastie.eu/2019/02/18/how-to-use-public-nordvpn-api/
      - QUERY=filters\[country_id\]=228&\[servers_groups\]\[identifier\]=legacy_p2p
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1   # Recomended if using ipv4 only
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - crowd
    ports:
      - 3128:3128     # squid
```

**Comment by leogout** [comment]
Hi, I have the exact same issue and @michaelkrieger 's answer did not fix it for me. I will keep my docker compose setup for now. Maybe I'll switch to k8s once I'm more familiar with it but it seems much more complicated than docker swarm is.

**Comment by ArmandBriere** [comment]
> Got this working by adding `INTERFACE=eth1` as a parameter.  This is a working config in swarm.  My swarm network is called `crowd`, so I add that network to the pot.
> 
> ```
>   nordlynx:
>     container_name: nordlynx
>     image: ghcr.io/bubuntux/nordlynx
>     cap_add:
>       - NET_ADMIN
>       - SYS_MODULE
>     environment:
>       # docker run --rm --cap-add=NET_ADMIN -e USER=... -e PASS='...' bubuntux/nordvpn:get_private_key
>       - PRIVATE_KEY=...
>       - NET_LOCAL=192.168.0.0/24
>       - INTERFACE=eth1
>       - TZ=America/NewYork
>       - "DNS=1.1.1.1,8.8.8.8" # Cloudflare with Google backup
>       # QUERY NordVPN API Cheat Sheet: https://sleeplessbeastie.eu/2019/02/18/how-to-use-public-nordvpn-api/
>       - QUERY=filters\[country_id\]=228&\[servers_groups\]\[identifier\]=legacy_p2p
>     restart: unless-stopped
>     sysctls:
>       - net.ipv6.conf.all.disable_ipv6=1   # Recomended if using ipv4 only
>       - net.ipv4.conf.all.src_valid_mark=1
>     networks:
>       - crowd
>     ports:
>       - 3128:3128     # squid
> ```

@michaelkrieger could you provide a full docker-stack.yml file as an example showing how you define a new service that routes the traffic through the vpn container? You `crowd` network configuration is also something I would like to see 

I spent some time trying to run a simple nginx container through the vpn without success. It seems that the internal port mapping is working but I don't find a way to expose my vpn service to the outside

**Comment by michaelkrieger** [comment]
> [@michaelkrieger](https://github.com/michaelkrieger) could you provide a full docker-stack.yml file as an example showing how you define a new service that routes the traffic through the vpn container? You `crowd` network configuration is also something I would like to see


```
networks:
  crowd:
    name: crowd
    driver: overlay
    attachable: true

services:
  squid:
    container_name: squid
    image: b4tman/squid
    restart: unless-stopped
    depends_on:
      nordlynx:
        restart: true
        condition: service_healthy
    volumes:
      - /srv/data/squid/my-squid.conf:/etc/squid/my-squid.conf:ro
      - /srv/data/squid/cache:/var/spool/squid
      - /srv/data/squid/log:/var/log/squid/
    environment:
      - "TZ=America/Toronto"
      - SQUID_CONFIG_FILE=/etc/squid/my-squid.conf
    network_mode: service:nordlynx
    # ports moved to NordLynx container
    # ports:
    #   - 3128:3128
    labels:
      - "traefik.enable=false"
      - "diun.enable=true"

  nordlynx:
    container_name: nordlynx
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # Generate PRIVATE_KEY with `docker run --rm --cap-add=NET_ADMIN -e USER=xxxxx -e PASS='xxxxxx' bubuntux/nordvpn:get_private_key`
      - PRIVATE_KEY=xxxxx
      # Home network IP range
      - NET_LOCAL=192.168.150.0/23
      - INTERFACE=eth1
      - TZ=America/Toronto
      - "DNS=1.1.1.1,8.8.8.8" # Cloudflare with Google backup
      # QUERY NordVPN API Cheat Sheet: https://sleeplessbeastie.eu/2019/02/18/how-to-use-public-nordvpn-api/
      - QUERY=filters\[country_id\]=38&\[servers_groups\]\[identifier\]=legacy_p2p       # Canada
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1   # Recomended if using ipv4 only
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - crowd
    ports:
      - 3128:3128     # squid
    labels:
      - "diun.enable=true"
      - "traefik.enable=false"
```
