### ISSUE TITLE
Moving from bubuntux/nordvpn

### ISSUE THREAD

**Issue by MRobi1** [bubuntux/nordlynx#9]
Looking for some guidance on replacing bubuntux/nordvpn with this instead based on this commend https://github.com/bubuntux/nordvpn/issues/282#issuecomment-969050986

I've got it up and running, it's connected, and I can connect other containers through it, I just can't seem to access them once they're connected. 

I'm looking for the equivalent environment variables for:
1: NETWORK=192.168.1.0/24  # So it can be accessed within the local network
2: CONNECT=Canada
3: KILLSWITCH=Enabled

Also looking for the proper way to set the ports for the containers connecting through this one. On the NordVPN one you'd set the ports for the containers through the NordVPN container (ie: 3000:3000), is this handled the same or can you use a comma seperated list for LISTEN_PORTS? 

The documentation isn't really clear on any of these.

**Comment by domi089** [comment]
I have the same questions. Maybe it can be solved with "QUERY" parameter?

**Comment by ThxAndBye** [comment]
`NETWORK` is named `NET_LOCAL` now but works the same.  

Instead of `CONNECT` you have to use the `QUERY` parameter but with the syntax used for the API at: https://api.nordvpn.com/v1/servers/recommendations   
E.g. for Switzerland it's `QUERY=filters\[country_id\]=209`, you just have to look up the country_id for Canada.  

Ports work exactly the same. It's just how docker works and not specific to the old NordVPN container or this one.

**Comment by cschinis** [comment]
> 

Have you managed to get this to work? I'm trying to do the same but struggling to make it work as it should. A guide & compose example for a working version would be really appreciated.

**Comment by ThxAndBye** [comment]
Yes, it now operates in the same way as the old nordvpn container did.
An example configuration is in the [README.md](https://github.com/bubuntux/nordlynx#usage) you only have to add the `QUERY` in the `environment: ` part where the `PRIVATE_KEY` is located.  
Not sure if there is a public list with all the country IDs though but the linked API does recommend servers from the same country as your connection. So, if you connect to a server in Switzerland and open the site, the servers in the list will display you the id for that country (209).

**Comment by cschinis** [comment]
Hi,

Thanks for this. This is my config which doesn't seem to work. Am I missing something? 

```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PUID=998
      - PGID=100
      - PRIVATE_KEY=[KEY HIDDEN]= #required
      - QUERY=filters\[country_id\]=227
      - NET_LOCAL=10.10.[XX].0/24  # So it can be accessed within the local network
      - ALLOWED_IPS=10.10.[YY].0/24,10.10.[ZZ].0/24
    volumes:
      - /srv/[PATH]/Configs/NordLynx:/config     
    ports:
      - 9292:9090 #Prometheus
      - 3000:3000 #Grafana   
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    restart: unless-stopped  
```

**Comment by ThxAndBye** [comment]
You don't need a volume for the configs. They get created dynamically on startup and don't need a permanent location.    
`PUID` and `PGID` probably don't do anything? It's also not really needed to change them at all as the processes will never interact with something outside the container directly.  

I don't understand why you only allow some private IPs. If you want traffic to run via the VPN connection then you should use the default `0.0.0.0/0`. Essentially you block all traffic because there is no IP addressable in this range behind the VPN.

**Comment by cschinis** [comment]
> You don't need a volume for the configs. They get created dynamically on startup and don't need a permanent location. `PUID` and `PGID` probably don't do anything? It's also not really needed to change them at all as the processes will never interact with something outside the container directly.
> 
> I don't understand why you only allow some private IPs. If you want traffic to run via the VPN connection then you should use the default `0.0.0.0/0`. Essentially you block all traffic because there is no IP addressable in this range behind the VPN.

Okay perfect! That all works as it should now. I misinterpreted what allowed IPs was. Thought it was the equivalent of firewall whitelisting. 

For future reference to others the working docker compose for me is :
`version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    cap_add:
      - NET_ADMIN #required
    environment:              
      - PRIVATE_KEY=[KEY HIDDEN]= #required
      - QUERY=filters\[country_id\]=227 #UK Servers
      - NET_LOCAL=10.10.[XX].0/24  # So it can be accessed within the local network
      - ALLOWED_IPS=0.0.0.0/0
    ports:
      - 9292:9090 #Prometheus
      - 3000:3000 #Grafana   
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    restart: unless-stopped  `

**Comment by Gandalf-** [comment]
I'm moving over from bubuntux/nordvpn as well and got close following @cschinis 's example. However
I'm seeing the same behavior (and same output from the same setup) as https://github.com/bubuntux/nordlynx/issues/10. I can access other containers with `network_mode: service:vpn` via the LAN but they (the dependent containers) can't get any traffic back from the WAN (including DNS).
```
version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PRIVATE_KEY=...
      - NET_LOCAL=10.1.10.0/24
      - ALLOWED_IPS=0.0.0.0/0
    ports:
      - 8090:8090 # torrent
      - ...
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1

  torrent:
    image: linuxserver/qbittorrent
    container_name: torrent
    network_mode: service:vpn
    restart: unless-stopped
    environment:
      - WEBUI_PORT=8090
      - ...
    volumes:
      - ...
    depends_on:
      - vpn
```
```
$ docker exec torrent curl -sS --verbose google.com
* Could not resolve host: google.com
* Closing connection 0
curl: (6) Could not resolve host: google.com
```
The docker host is on Ubuntu 18.04.6, 4.15.0-163-generic if that helps

**Comment by cschinis** [comment]
Don't forget to add:
`      - QUERY=filters\[country_id\]=227 #UK Servers`

Change the ID to your recommended server id from (Example extract for UK "{"id":**227**,"name":"United Kingdom","code":"GB","):
https://api.nordvpn.com/v1/servers/recommendations

**Comment by Gandalf-** [comment]
Thanks for the reply! Neither of those changes affect the behavior unfortunately. Neither the vpn container or the dependent containers can access the WAN

Unrelatedly, I thought the QUERY var was optional and it'd auto select the best by default?

**Comment by cschinis** [comment]
> Thanks for the reply! Neither of those changes affect the behavior unfortunately. Neither the vpn container or the dependent containers can access the WAN
> 
> Unrelatedly, I thought the QUERY var was optional and it'd auto select the best by default?

How are you deploying the stack? With the exception of the issue I had above which was resolved with allowing 0.0.0.0, every other time dependant containers were not connecting to the wan was because the vpn did not have a successful connection.

I use docker in combination with Portainer and similar issues were fixed by stopping all containers, deleting the images and networks and redeployed the stack. Obviously make sure the private key is correct.

**Comment by haygoodhtpc** [comment]
Does anyone have a compose that they can use that funnels Qbittorrent through the VPN? Here's the stack I'm using through portainer and everything launches but I can't see Qbittorrent on :8080. 

`#torrent stack
version: "3.7"
services:
    vpn:
        image: ghcr.io/bubuntux/nordlynx
        cap_add:
           - NET_ADMIN #required
        container_name: nordlyx
        environment:
           - PRIVATE_KEY=[HIDDEN] #required
           - QUERY=filters\[country_id\]=209 #Switzerland
           - NET_LOCAL=192.168.1.0/24  # So it can be accessed within the local network
           - ALLOWED_IPS=0.0.0.0/0
        sysctls:
           - net.ipv6.conf.all.disable_ipv6=0
        restart: unless-stopped
    torrent:
        container_name: qbittorrent
        image: cr.hotio.dev/hotio/qbittorrent
        network_mode: service:vpn
        depends_on:
           - vpn
        environment:
           - PUID=1001
           - PGID=1001
           - UMASK=002
           - TZ=America/Chicago
           - WEBUI_PORT=8080
        volumes:
           - /opt/qbittorrent:/config
           - /mnt/media/downloads:/downloads
        restart: always           `

**Comment by NoLooseEnds** [comment]
I'm having issues with this too.

Testing with the bare minimum:
```
version: '3.7'

services:
  vpn-test:
    container_name: nordlynx
    image: ghcr.io/bubuntux/nordlynx:edge
    cap_add:
        - NET_ADMIN #required
    environment:
        - PRIVATE_KEY=<key>
        - NET_LOCAL=10.0.0.0/24 # So it can be accessed within the local network
        - ALLOWED_IPS=0.0.0.0/0
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
```

This allows me to i.e `ping 10.0.0.1` on the local network, but I'm not allowed to ping or resolve anything else.

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/4103531/146690493-8021fc65-8df9-45e0-b86d-d174e036334a.png">
